<?php
// Start the session
session_start();
// Check user login or not
if(!isset($_SESSION["user"]) ||  $_SESSION['annotation_mode'] != 'evidence'){
    include file_get_contents('index.php');
    echo "<!--";
}
?>

<html>
<head>
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />


  <script src="js/extensions/jquery.js"></script>
  <script src="js/extensions/jquery.md5.js"></script>
  <script src="js/extensions/jquery_ui.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

  <script src="js/editable-select.js"></script>
  <script src="js/highlighter.js"></script>
  <script src="js/evidence_annotation.js"></script>


</head>

<body style="font-family: sans-serif">

  <div class="topnav" id="myTopnav">
    <a href="user-details.php" id="user-details" class="fa fa-user-circle-o">User Details</a>
    <a href="annotation_guidelines/Evidence_annotation/main.pdf" class="fa fa-file-pdf-o" target="_blank">Annotation Guidelines</a>
    <a href="" class="logout fa fa-sign-out" style="text-align:right">Logout</a>
  </div>

  <div class="menu-frame grid-container" id="my-menu-frame">

  <!-- <p class="label-current-claim center">Current claim:</p> -->
<div class="current-claim-div font-weight-bold text-uppercase grid-item">

<button id= 'go-back' class="btn btn-primary fa fa-arrow-circle-left fa-lg pull-left"></button>
<button id= 'go-forward' class=" btn btn-primary fa fa-lg fa-arrow-circle-right pull-left" disabled></button>
<p class="label-current-claim center text-capitalize"> <button type="button" class="btn btn-sm btn-info small h-5 fa fa-info rounded-circle rounded-sm" data-toggle="popover" title="Claim" data-content=	" The given claim is a one-sentence factoid generated by annotators based on Wikipedia in a previous annotation task. If a claim is not verifiable (e.g. due to being subjective or not being grammatical) you can report the claim using the appropriate button.)  "></button> Current claim:</p>
<p id="current-claim" class="text-center text-danger" > </p>
</div>

<div class="grid-item">


<!-- <input type="text" class='generated-claim-question' id='generated-question1' placeholder="Question 1" size='50em' value="">
<input type="text" class='generated-claim-answer' id='generated-answer1' placeholder="Answer 1" size='10em' value="">
<br>
<input type="text" class='generated-claim-question' id='generated-question2' placeholder="Question 2" size='50em' value="">
<input type="text" class='generated-claim-answer' id='generated-answer2' placeholder="Answer 2" size='10em' value="">
<br>
<input type="text" class='generated-claim-question' id='generated-question3' placeholder="Question 3" size='50em' value="">
<input type="text" class='generated-claim-answer' id='generated-answer3' placeholder="Answer 3" size='10em' value="">
<br>
<input type="text" class='generated-claim-question' id='generated-question4' placeholder="Question 4" size='50em' value="">
<input type="text" class='generated-claim-answer' id='generated-answer4' placeholder="Answer 4" size='10em' value="">
<br>
<span> Can your questions/answers directly verify the claim?</span>
<select id="question-enough-selector" class = 'select-menu'>
   <option value="h" selected disabled hidden>Nothing selected</option>
  <option value="yes">Yes</option>
  <option value="no">No</option>
</select> -->

</div>

<!-- <label for="annotated-evidence-div" id="annotated-evidence-div-label">Currently annotated evidence:</label> -->
<div class="annotated-evidence-div-sets grid-item">
<button type="button" class="btn btn-sm btn-info small h-5 fa fa-info rounded-circle rounded-sm pull-left" data-toggle="popover" data-html="true" title="Evidence Annotation" data-content=" Click on relevant information in either text, table, or lists anywhere on wikipedia to be added as evidence. Read section 3 of the guidelines in detail and look at the provided examples! <br> <ul>
<li> You are able to find three evidence sets here. Their purpose is to allow you to create multiple sets of evidence. This is needed for the situation in which you collected enough evidence to either support or refute a claim but found new evidence that is able to support or refute the claim independently from your already annotated evidence.
<li> In case the highlighted sentence/cells/items additionally requires knowledge of the article's title, section header, or table caption,} the part has to be \textbf{explicitly highlighted.
<li> You can navigate freely on any page of this Wikipedia, however, for navigation you are only allowed to use either the available Wikipedia search field, page search field, or hyperlinks in articles. <b>Do not use your browser navigation tools (e.g. CTRL + F) for navigation <b>.
</ul>"></button>
<button id="set1" class="evidence-set btn btn-sm"> Set 1:  <span class="fa-stack">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-file-text fa-stack-1x fa-inverse"></i>
</span> </button>
&ensp;&ensp;
<button  id="set2" class="evidence-set btn btn-sm"> Set 2:<span class="fa-stack">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-file-text fa-stack-1x fa-inverse"></i>
</span></button>
&ensp;&ensp;
<button  id="set3" class="evidence-set btn btn-sm"> Set 3:
<span class="fa-stack">
<i class="fa fa-circle fa-stack-2x"></i>
<i class="fa fa-file-text fa-stack-1x fa-inverse"></i>
</span></button>

<div class="annotated-evidence-div">
</div>
</div>
<!-- <div class="annotated-evidence-div">
</div> -->

<div class="evidence-annotation-verdict grid-item">
<!-- <button data-toggle="tooltip" title='Evidence Retrieval} A challenge to verify the claim will be the retrieval of required evidence, e.g. for the Claim "\emph{Non college educated voters voted 67 percent for the democratic party in 1952}" the evidence is located on the page "New Deal Coalition" -- challenging to deduce the page based on the claim.' class="btn btn-info fa fa-question"></button> -->

<button type="button" class="btn btn-sm btn-info small h-5 fa fa-info rounded-circle rounded-sm" data-toggle="popover" title="Verification Challenges" data-content=	"We are interested in gaining more insights into what challenges the annotator had for finding evidence for the given claim. You can select one or multiple of the given challenge categories and also add your own terms to describe any challenges not captured by the options given."></button>
<span> Challenges:</span>
<select id="evidence-annotation-challenge-selector" class="selectpicker" multiple>
  <!-- <option value="h" selected disabled hidden>Choose here</option> -->
  <option value="Evidence Retrieval">Evidence Retrieval</option>
  <option value="Ambiguity">Ambiguity</option>
  <option value="Multi-hop Reasoning">Multi-hop Reasoning</option>
  <option value="Commonsense Reasoning">Commonsense Reasoning</option>
  <option value="Linguistic Inference">Linguistic Inference</option>
  <option value="Numerical Reasoning">Numerical Reasoning</option>
  <option value="Reasoning over Structure">Reasoning over Structure</option>
  <option value="Combining List/Table and Text">Combining List/Table and Text</option>
  <option value="None">None</option>
</select>
&nbsp;
&nbsp;
&nbsp;
&nbsp;
<button type="button" title="Verdict" class="btn btn-sm btn-info small h-5 fa fa-info rounded-circle rounded-sm" data-toggle="popover" data-html="true" data-content=	"
<ul>
<li> Ask yourself: If I was given only the selected sentences, table cells, and list items, do I have strong enough reason to believe the claim is supported or strong enough reason to believe the claim is refuted. If I’m not certain, what additional information do I have to add to reach this conclusion and can I find it on Wikipedia? If I cannot find the required evidence, then the claim should be marked as NotEnoughInformation.
<li> If a claim is marked as NotEnoughInformation please still submit the evidence found in the process of reaching this verdict!
</ul>
"></button>
<span> Verdict:</span>
<select id="evidence-annotation-verdict-selector">
   <option value="h" selected disabled hidden>Nothing selected</option>
  <option value="Supported">Supported</option>
  <option value="Refuted">Refuted</option>
  <option value="Not enough Information">Not enough Information</option>
</select>
<br>
<br>
<br>
<br>
<div class="evidence-annotation-submit input-group-prepend">
  <!-- <button class="evidence-annotation-submit-button fa fa-check btn btn-success" aria-hidden="true"> Submit Annotation </button> -->
<button class="evidence-annotation-submit-button fa fa-check btn btn-success"> Submit Annotation </button>
&nbsp;
&nbsp;
&nbsp;
&nbsp;
<!-- <button class="evidence-annotation-report-button fa fa-exclamation-triangle btn btn-warning"> Report Claim </button> -->
<button type="button" id='report-button' class="btn btn-warning fa fa-exclamation-triangle">Report</button>
<button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
  <span class="sr-only">Toggle Dropdown</span>
</button>
<!-- <select id="evidence-annotation-report" class="selectpicker" data-style="btn-warning"> -->
  <div class="dropdown-menu">
  <!-- <option class="dropdown-item"  selected disabled hidden value="NEI"> Report Claim</option> -->
  <a class="dropdown-item report-item"  value="NEI">Cannot be verified using any publicly available information </a>
  <a class="dropdown-item report-item" value="NEI">Does not meet the claim generation guidelines</a>
  <a class="dropdown-item report-item"  value="supported">Ungrammatical, spelling mistakes, typographical errors</a>
  <input id= 'report-note' class="dropdown-item" placeholder='Enter Note...'>
</div>
</div>

</div>
</div>
</body>
</html>
